###############################################################################
# Java __APP__ service for testing purpose.
#
# Run as a daemon with:
# docker run -d -p 80:8080 quay.io/legdba/httpecho:[tag]
#
# To get the list of supported arguments run
# docker run -ti --rm -p 80:8080 quay.io/legdba/httpecho:[tag] --help
#
# TODO: force JVM kill upon OOM
#
###############################################################################
FROM azul/zulu-openjdk-debian:8
MAINTAINER Vincent Bourdaraud <vincent@bourdaraud.com>

# Prepare for service (dirs, user, port, command)
RUN mkdir /opt/__APP__ && \
    groupadd -r __APP__ && \
    useradd -r -g __APP__ __APP__
WORKDIR /opt/__APP__
CMD ["-p", "8080"]
ENTRYPOINT ["java", "-jar", "/opt/__APP__/__APP__-all.jar"]
EXPOSE 8080

# Add Java App (copy one by one because of a bug on Docker 1.2-circleci on
# CircleCI causing multi-copy to skip some files and store them the wrong place)
COPY __FATJAR__ /opt/__APP__/
COPY __FATJAR__.sha1 /opt/__APP__/
COPY Dockerfile /opt/__APP__/
RUN sha1sum -c __FATJAR__.sha1 && \
    ln -s __FATJAR__ __APP__-all.jar && \
    java -jar __APP__-all.jar --help
USER __APP__